name: "Terraform GitHub Actions"
on:
  push:
    branches-ignore:
      - master
jobs:
  terraform:
    name: "Terraform Init"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master 
      - name: "Terraform Initialization"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: "init"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  secondjob:
    name: "Terraform  Format"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master 
      - name: "Terraform Initialization"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: "fmt"
  
       
