name: "Terraform GitHub Actions"
on:
  pull_request:
  push:
    branches:
      - terraform/ResourceGroup
jobs:
  terraform:
    name: "Terraform Init"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master 
      - name: "Terraform Initialization"
        uses: hashicorp/terraform-github-actions@master 
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: "init"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  shelljob:
    name: "Demo"
    runs-on: ubuntu-latest
    steps:
     - name: "Shell Demo"
       run: curl www.googl.com
       shell: bash
  
       
